repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        pass_filenames: false

      - id: ruff
        name: ruff
        description: "Run 'ruff' for extremely fast Python linting"
        entry: poetry run ruff check
        language: system
        types_or: [ python, pyi ]
        args: [--fix]
        require_serial: true
        additional_dependencies: [ ]
        minimum_pre_commit_version: "2.9.2"

      - id: ruff-format
        name: ruff-format
        description: "Run 'ruff' for extremely fast Python linting"
        entry: poetry run ruff format
        language: system
        types_or: [ python, pyi ]
        args: [ ]
        require_serial: true
        additional_dependencies: [ ]
        minimum_pre_commit_version: "2.9.2"